### ISSUE TITLE
required parameter $increment is missing in call to function modular-scale

### ISSUE THREAD

**Issue by glencampbell** [lacroixdesign/node-bourbon#13]
I am using grunt-sass, which uses node-sass/libsass. So, I have installed both grunt-sass and node-sass. I then use `includePaths: bourbon.includePaths` in my sass options, with `var bourbon = require('node-bourbon');` at the top of the Grunt.js file.

I `@import: 'bourbon';` at the start of my sheet, which is not throwing up any error. I have a modular approach to my file setup with @import pulling in files, that @import smaller _banner.scss, etc files. Then I have my sass task pointed at the main file that needs processed, compiled and output to css.

I am using the modular-scale mixin…

When I use it like so: `modular-scale(3)`, I am getting the following console error:

`required parameter $increment is missing in call to function modular-scale`

But, when I specify all the values, e.g. `modular-scale(3, 14px, $modular-scale-ratio)`, it processes fine.

I also notice some mixins are not recognised, e.g. text-decoration. 

Does this sound like I have a problem with my setup? (I was using grunt-contrib-sass, and have switched to grunt-sass)

I am using compass's Jacket as a standalone via bower, so thought it may be to do with this – but even if I move the code outside Jacket, same error.

Thanks!
-g

**Comment by glencampbell** [comment]
Bump

**Comment by iamlacroix** [comment]
Hey! Sorry for the delay, it's been busy around here. We are currently tracking Bourbon 3.2.x since there were incompatibilities with Libsass and Bourbon 4.x. The default values feature for `modular-scale` was [added in 4.1.0](https://github.com/thoughtbot/bourbon/releases/tag/v4.1.0).

That said, the release of Libsass 3.1 [brings it much closer to Ruby Sass' features](https://github.com/sass/libsass/releases/tag/3.1.0), and the 2.0 of beta node-sass appears to incorporate that version. I'll be re-evaluating the 4.x branch once that releases.

**Comment by glencampbell** [comment]
Brilliant, thanks Michael!

On 20 January 2015 at 05:06, Michael LaCroix <notifications@github.com>
wrote:

> Hey! Sorry for the delay, it's been busy around here. We are currently
> tracking Bourbon 3.2.x since there were incompatibilities with Libsass and
> Bourbon 4.x. The default values feature for modular-scale was added in
> 4.1.0 <https://github.com/thoughtbot/bourbon/releases/tag/v4.1.0>.
>
> That said, the release of Libsass 3.1 brings it much closer to Ruby Sass'
> features <https://github.com/sass/libsass/releases/tag/3.1.0>, and the
> 2.0 of beta node-sass appears to incorporate that version. I'll be
> re-evaluating the 4.x branch once that releases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lacroixdesign/node-bourbon/issues/13#issuecomment-70605222>
> .
>



-- 
-----------------------------------------------------------

Glen Campbell
Web Designer

Belfast, Northern Ireland

M: 07784 413 526

www.madewithmotive.com

uk.linkedin.com/in/mrglencampbell

-----------------------------------------------------------
