### ISSUE TITLE
Cant use some Bourbon Mixins

### ISSUE THREAD

**Issue by mikemcguire** [lacroixdesign/node-bourbon#14]
Having issues getting access to most mixing, started noticing this when I tried using some of the Refills examples. I've tried using both grunt-contrib-sass and grunt-sass... My first issue was with a mixin whose name had changed but then I started grabbing some mixins from the Bourbon documentation. Some are working some aren't. 
My grunt configuration looks like this

```
sass: {
	dist: {
	  	options: {
	    	style: 'compressed',
	    	includePaths: require('node-bourbon').includePaths.concat(require('node-neat').includePaths),
	  	},
		files: {
	    	'build/css/main.css': 'application/scss/main.scss', 
	    }
	}
},

```

The errors that I  am getting

```
no mixin named flex-wrap,
no mixin named calc,
no mixin named flex-direction
```
These are just a few that I found. I didnt test all of them, but mixins for linear-gradient, display-context, hidpi, hyphens  all work just fine. Am I missing something obvious here?

**Comment by iamlacroix** [comment]
@mikemcguire Which version is installed in `YOUR_PROJECT/node_modules/node-bourbon/package.json`? We are tracking Bourbon proper v3.2.x, so the flexbox mixins should be working (I use them myself!).

**Comment by mikemcguire** [comment]
1.2.3, I actually saw earlier that I was using 1.0.0 and upgraded with the same behavior.

**Comment by mikemcguire** [comment]
I've been poking around with a bunch of stuff making sure I had the dependencies for node-bourbon, blah, blah, blah and now it's compiling fine... Not sure what fixed it but I am going to assume a user error. Sorry for the mix-up.

**Comment by iamlacroix** [comment]
No worries, glad it's working!
