### ISSUE TITLE
node-bourbon is outdated

### ISSUE THREAD

**Issue by axelson** [lacroixdesign/node-bourbon#16]
The current version of bourbon is now 4.2.1 and it appears that node-bourbon is still on 3.2.1, are there plan to update node-bourbon?

https://github.com/thoughtbot/bourbon/releases

**Comment by iamlacroix** [comment]
Official bourbon now supports Libsass, so I've migrated this library to a wrapper of that. The main focus/purpose going forward will simply be the convenience helpers to get the directory path.

I've just published `4.2.1-beta1`, feel free to try that in your projects. Note that the official bourbon requires Libsass 3.1, so you'll need to ensure you're using node-sass 2.0+
