### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by azaslavsky** [lacroixdesign/node-bourbon#24]
Hey,
  When using node-bourbon, the following code produced an error that broke `gulp watch` in NPM (ie, didn't even return an error callback, and ended the `watch` process).  The error spit back by the CLI was `Segmentation fault: 11`, when my code looked like this:

```scss
.framing {
	@include position(absolute, calc(10% - #{$ctrlHeight/2}) 0 calc(10% - #{$ctrlHeight/2}) %50);
}
```

Obviously I made a typo when I put `%50` for the fourth position value there, but it still shouldn't break without returning an error message.  Writing the code correctly fixed the problem, but the fact that it broke my watcher was pretty frustrating.  Using version 4.2.3 off of NPM.  Let me know if there is any other information I can provide.

Edit: I should add that I love this library and am very grateful that you guys put it together - it speeds up development enormously.  Thanks!

**Comment by iamlacroix** [comment]
Hey thanks for posting this! The Sass compilation is performed by [node-sass](https://github.com/sass/node-sass), so problems like this would be handled upstream. From a quick glance, [this issue](https://github.com/sass/node-sass/pull/366) might be related, however I didn't dig too deep.

Hope this helps!
