### ISSUE TITLE
Bourbon-path broken with 4.2.6 and Grunt.

### ISSUE THREAD

**Issue by coreequip** [lacroixdesign/node-bourbon#27]
The Bourbon-package changes the way of exporting the path-information. Following code solved the problems on my side:

```javascript
var path = require('path');
var bourbon = require('bourbon');

module.exports = {

  includePaths: [bourbon.includePaths],

  with: function() {
    var paths  = Array.prototype.slice.call(arguments);
    return [].concat.apply([bourbon.includePaths], paths);
  }

};

```

**Comment by pl7y** [comment]
Even for me bourbon paths are broken: include path is `node_modules/bourbon`, but it works only if I manually adjust it like `node_modules/bourbon/app/assets/stylesheets` (so that I can do `import 'bourbon' `in scss).
Probably related to #28 .

**Comment by pl7y** [comment]
Don't know really, but it looks like it's related to this bourbon [commit](https://github.com/thoughtbot/bourbon/commit/c76215be98f2fa3ef9c5ed2174765a316c96747b).

**Comment by coreequip** [comment]
Hi Andrea,

the bourbon-people uses now a standard pattern to "export" a property (here the includePaths).

What happened:
node-burbon referred to bourbon-v4.2.3 which doesn't use this pattern so they had to "resolve" the package path and uses this as include path. Works well until this happened:

[This commit](https://github.com/lacroixdesign/node-bourbon/commit/58ca5989e67e74849f96c95414fcedd32f5e88c4) just increases the bourbon-version to 4.2.6. But in 4.2.4 they changed a lot. Btw: I wonder why the tests don't break.

**Comment by pl7y** [comment]
Thanks for the prompt reply!
Good observation with the tests, they should definitely fail.

**Comment by pl7y** [comment]
Hi @coreequip, I just tested your solution above and it works.

**Comment by pl7y** [comment]
Would you contribute to the repo with the change?

**Comment by coreequip** [comment]
Yes. I'll send later a pullrequest.

**Comment by coreequip** [comment]
See my changes, thats the reason why the tests didn't fail. But its fixed now. :-)

**Comment by pl7y** [comment]
I confirm your pull request is working!

**Comment by iamlacroix** [comment]
I've just published v4.2.7 to npm, let me know if that works. Thanks again for your PR! If the latest release is working, I'll go ahead and close this.

**Comment by pl7y** [comment]
For me, it works. Thanks!

**Comment by iamlacroix** [comment]
Great!
