### ISSUE TITLE
bourbon.includePaths is returning an array within an array

### ISSUE THREAD

**Issue by Robert-Frampton** [lacroixdesign/node-bourbon#30]
As it is documented, bourbon.includePaths should return an array of Bourbon paths. Currently it is returning an array with a child array that contains the paths. For example...

```js
[ [ '/node_modules/bourbon/app/assets/stylesheets' ] ]
```

node-bourbon version: 4.2.7
node version: 5.5.0
npm version: 3.3.12
os: OSX El Capitan

**Comment by iamlacroix** [comment]
Thanks for the heads-up! Just pushed a fix in v4.2.8.

**Comment by Robert-Frampton** [comment]
Thanks for the quick fix @iamlacroix
