### ISSUE TITLE
Unable to import Bourbon to stylesheet

### ISSUE THREAD

**Issue by ssosina** [lacroixdesign/node-bourbon#38]
I recently did an update to my package.json. Upon importing Bourbon to my scss stylesheet I ran into the following `Error: File to import not found or unreadable: bourbon`. 

Within my node-modules, I can see that I have a node-bourbon and bourbon folder. My gulpfile.js has not changed since the update.

I need to understand and fix this for a project I'm currently working on so any help will be appreciated. 

**Package.json file**
```
 "devDependencies": {
    "browser-sync": "^2.12.8",
    "gulp": "^3.9.1",
    "gulp-sass": "^3.1.0",
    "node-bourbon": "^4.2.8",
    "node-neat": "^2.0.0-beta.0"
  }
}
```

**Gulpfile.js**
```
var gulp        = require('gulp');
var browserSync = require('browser-sync').create();
var sass        = require('gulp-sass');
var bourbon 	= require("node-bourbon").includePaths;
var neat 		= require("node-neat").includePaths;

// Static Server + watching scss/html files
gulp.task('serve', ['sass'], function() {

    browserSync.init({
        server: "./app"
    });

    gulp.watch("app/scss/**/*.scss", ['sass']);
    gulp.watch("app/*.html").on('change', browserSync.reload);
});

// Compile sass into CSS & auto-inject into browsers
gulp.task('sass', function() {
    return gulp.src("app/scss/*.scss")
        .pipe(sass({
        	includePaths: bourbon,
        	includePaths: neat
      	}))
        .pipe(gulp.dest("app/css"))
        .pipe(browserSync.stream());
});

gulp.task('default', ['serve']);

```

**Comment by lougreenwood** [comment]
Any luck, I'm trying to use node-bourbon for the first time and I'm getting the same issue...

**Comment by ssosina** [comment]
Yeah, @lougreenwood this was resolved. See Gulpfile.js in my [starter-project repo](https://github.com/ssosina/starter-project)
